from pyiceberg.schema import Schema
from pyiceberg.types import BooleanType, DoubleType, LongType, NestedField, StringType, TimestamptzType

COMPUTE_OFFERS_BRONZE_SCHEMA = Schema(
    NestedField(field_id=1, name="offer_id", field_type=LongType(), required=True),
    NestedField(field_id=2, name="machine_id", field_type=LongType(), required=True),
    NestedField(field_id=3, name="host_id", field_type=LongType(), required=True),
    NestedField(field_id=4, name="offer_type", field_type=StringType(), required=True),
    NestedField(field_id=5, name="total_price_usd_per_hr", field_type=DoubleType(), required=True),
    NestedField(field_id=6, name="gpu_price_usd_per_hr", field_type=DoubleType(), required=True),
    NestedField(field_id=7, name="minimum_bid_price_usd", field_type=DoubleType(), required=False),
    NestedField(field_id=8, name="storage_cost_usd_per_hr", field_type=DoubleType(), required=False),
    NestedField(field_id=9, name="network_upload_cost_usd_per_gbit", field_type=DoubleType(), required=False),
    NestedField(field_id=10, name="network_download_cost_usd_per_gbit", field_type=DoubleType(), required=False),
    NestedField(field_id=11, name="deep_learning_score_per_usd", field_type=DoubleType(), required=True),
    NestedField(field_id=12, name="gpu_architecture", field_type=StringType(), required=True),
    NestedField(field_id=13, name="gpu_model_name", field_type=StringType(), required=True),
    NestedField(field_id=14, name="gpu_memory_mb", field_type=DoubleType(), required=True),
    NestedField(field_id=15, name="gpu_tdp_watts", field_type=DoubleType(), required=False),
    NestedField(field_id=16, name="number_of_gpus", field_type=LongType(), required=True),
    NestedField(field_id=17, name="gpu_max_cuda_version_supported", field_type=DoubleType(), required=False),
    NestedField(field_id=18, name="gpu_tflops", field_type=DoubleType(), required=False),
    NestedField(field_id=19, name="gpu_bandwidth_gbytes_per_sec", field_type=DoubleType(), required=False),
    NestedField(field_id=20, name="cpu_architecture", field_type=StringType(), required=False),
    NestedField(field_id=21, name="cpu_model_name", field_type=StringType(), required=False),
    NestedField(field_id=22, name="number_of_cpu_cores", field_type=DoubleType(), required=False),
    NestedField(field_id=23, name="cpu_clock_speed_ghz", field_type=DoubleType(), required=False),
    NestedField(field_id=24, name="ram_mb", field_type=DoubleType(), required=True),
    NestedField(field_id=25, name="disk_model_name", field_type=StringType(), required=False),
    NestedField(field_id=26, name="disk_space_gb", field_type=DoubleType(), required=True),
    NestedField(field_id=27, name="disk_bandwidth_mbytes_per_sec", field_type=DoubleType(), required=False),
    NestedField(field_id=28, name="pcie_generation", field_type=DoubleType(), required=False),
    NestedField(field_id=29, name="pcie_bandwidth_gbytes_per_sec", field_type=DoubleType(), required=False),
    NestedField(field_id=30, name="network_download_mbits_per_sec", field_type=DoubleType(), required=True),
    NestedField(field_id=31, name="network_upload_mbits_per_sec", field_type=DoubleType(), required=True),
    NestedField(field_id=32, name="reliability_score", field_type=DoubleType(), required=False),
    NestedField(field_id=33, name="deep_learning_score", field_type=DoubleType(), required=False),
    NestedField(field_id=34, name="geolocation", field_type=StringType(), required=False),
    NestedField(field_id=35, name="verification_flag", field_type=StringType(), required=True),
    NestedField(field_id=36, name="rentable_flag", field_type=BooleanType(), required=True),
    NestedField(field_id=37, name="rented_flag", field_type=BooleanType(), required=True),
    NestedField(field_id=38, name="ingested_at", field_type=TimestamptzType(), required=True),
)
