sources:
  vast_ai:
    enabled: true
    poll_interval_seconds: 1800
    base_url: "https://console.vast.ai/api/v0"
    topic_name: "compute_offers"
    limit: 20000
    subdirectory_name: "VastAI"
    file_name: "compute_offers"

  exchange_rate:
    enabled: true
    poll_interval_seconds: 3600
    base_url: "https://v6.exchangerate-api.com/v6"
    from_currency: "USD"
    to_currency: "MKD"
    topic_name: "exchange_rate"
    subdirectory_name: "ExchangeRate"
    file_name: "exchange_rate"

seeds:
  erc:
    enabled: true
    url: "https://www.erc.org.mk/ceni.aspx"
    data: { "e": 2 }
    file_name: "electricity_tariffs"

  evn:
    enabled: true
    url: "https://www.evn.mk/Invoices.aspx#s4"
    file_name: "electricity_tariffs_schedule"
    expected_schedule_text: >
      Ниската тарифа е од 13:00 до 15:00 часот и од 22:00 до 07:00
      часот секој ден, како и од 22:00 часот (сабота) до 07:00
      часот (понеделник) преку викенд.

  open_db_cpu:
    enabled: true
    subdirectory_name: "CPU"
    file_name: "cpu_specifications"

  open_db_gpu:
    enabled: true
    subdirectory_name: "GPU"
    file_name: "gpu_specifications"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

http:
  timeout_seconds: 30
  retry_count: 5
  retry_delay_seconds: 60

kafka:
  bootstrap_servers: "localhost:29092"

paths:
  base_directory_path: "../data"
  open_db_subdirectory_path: "buildcores-open-db/open-db"
  seeds_directory_name: "seeds"
  sources_directory_name: "sources"
  checkpoints_directory_name: "checkpoints"