execution_type: "local"
sources:
  vast_ai:
    enabled: true
    base_url: "https://console.vast.ai/api/v0"
    limit: 10000
    file_name: "compute_offers"

  exchange_rate:
    enabled: true
    base_url: "https://v6.exchangerate-api.com/v6"
    from_currency: "USD"
    to_currency: "MKD"
    file_name: "exchange_rates"

seeds:
  erc:
    enabled: true
    url: "https://www.erc.org.mk/ceni.aspx"
    data: { "e": 2 }
    file_name: "electricity_tariff_prices"

  evn:
    enabled: true
    url: "https://www.evn.mk/Invoices.aspx#s4"
    file_name: "electricity_tariffs_schedule"
    expected_schedule_text: >
      Ниската тарифа е од 13:00 до 15:00 часот и од 22:00 до 07:00
      часот секој ден, како и од 22:00 часот (сабота) до 07:00
      часот (понеделник) преку викенд.
      Според одлуките на Регулаторната комисија за енергетика и водни услуги на Република Северна Македонија,
      цените ќе се применуваат почнувајќи од 01.01.2026.

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

http:
  timeout_seconds: 30
  retry_count: 5
  retry_delay_seconds: 60

paths:
  base_directory_path: "../data"
  seeds_directory_name: "seeds"
  sources_directory_name: "sources"

gcp:
  project_id: "ai-compute-arbitrage-monitor"
  region_name: "europe-west3"
  gcs:
    bucket_name: "ai-compute-arbitrage-monitor-lake"
  dataproc:
    image_tag: "europe-west3-docker.pkg.dev/ai-compute-arbitrage-monitor/ai-compute-arbitrage-monitor-repository/ai-compute-arbitrage-monitor-dataproc-image:latest"
    runtime_packages: ["common", "config", "refine"]
    entrypoints_path: "src/refine/pipelines"
    subnetwork_name: "projects/ai-compute-arbitrage-monitor/regions/europe-west3/subnetworks/ai-compute-arbitrage-monitor-subnet"
    service_account_email: "dataproc-sa@ai-compute-arbitrage-monitor.iam.gserviceaccount.com"
