FROM us-central1-docker.pkg.dev/cloud-dataproc/spark/dataproc_2.2

USER root

WORKDIR /app

RUN conda create -n spark_env python=3.11 -y && \
    conda clean -afy

RUN /opt/conda/envs/spark_env/bin/pip install --no-cache-dir \
    pyyaml pydantic python-dotenv

ENV SETTINGS_PATH="settings.yaml"
ENV PYSPARK_PYTHON=/opt/conda/envs/spark_env/bin/python

USER $DATAPROC_USER