transform:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: graphic-mission-505412-j7
      dataset: ai_compute_arbitrage_monitor_dataset
      threads: 4
      location: EU
      priority: interactive
  target: dev
