transform:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ai-compute-arbitrage-monitor
      dataset: ai_compute_arbitrage_monitor_dataset
      threads: 4
      location: EU
      priority: interactive
  target: dev
