name: Build & Push Composer Image

on:
  push:
    branches:
      - master
    paths:
      - "infra/terraform/Dockerfile.composer"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION_NAME: ${{ vars.GCP_REGION_NAME }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
  COMPOSER_NAME: ${{ vars.GCP_COMPOSER_ENVIRONMENT_NAME }}
  REPOSITORY_NAME: ${{ vars.GCP_REPOSITORY_NAME }}
  IMAGE_NAME: ${{ vars.GCP_COMPOSER_IMAGE_NAME }}

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER_NAME }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION_NAME }}-docker.pkg.dev --quiet

      - name: Build & Push Image
        id: build
        run: |
          IMAGE=${{ env.REGION_NAME }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker build \
            -f infra/terraform/Dockerfile.composer \
            -t $IMAGE:$SHORT_SHA \
            -t $IMAGE:latest \
            .
          docker push $IMAGE:$SHORT_SHA
          docker push $IMAGE:latest

      - name: Update Composer custom image
        run: |
          gcloud composer environments update ${{ env.COMPOSER_NAME }} \
            --location=${{ env.REGION_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --update-airflow-configs=core-custom_image=$IMAGE:$SHORT_SHA