name: Build & Push Dataproc Image

on:
  push:
    branches:
      - master
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "infra/terraform/Dockerfile.dataproc"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION_NAME: ${{ vars.GCP_REGION_NAME }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
  REPOSITORY_NAME: ${{ vars.GCP_REPOSITORY_NAME }}
  IMAGE_NAME: ${{ vars.GCP_DATAPROC_IMAGE_NAME }}

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER_NAME }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION_NAME }}-docker.pkg.dev --quiet

      - name: Build & Push image
        run: |
          IMAGE=${{ env.REGION_NAME }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
          docker build \
            -f infra/terraform/Dockerfile.dataproc \
            -t $IMAGE:$(git rev-parse --short HEAD) \
            -t $IMAGE:latest \
            .
          docker push $IMAGE:$(git rev-parse --short HEAD)
          docker push $IMAGE:latest