name: Deploy to Dataproc

on:
  push:
    branches:
      - master
    paths:
      - "src/refine/**"
      - "src/config/**"
      - "src/common/**"
      - "config/settings.yaml"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION_NAME: ${{ vars.GCP_REGION_NAME }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}

jobs:
  sync:
    name: Sync Jobs & Files
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER_NAME }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Sync to Dataproc
        run: python scripts/package_dataproc_modules.py